### ISSUE TITLE
Issues:

### ISSUE THREAD

**Issue by EmmaSweeney** [drgrigg/charles-dickens_the-life-and-adventures-of-nicholas-nickleby#1]
# General Issues:

- [x] Re-run `se build-images .` and commit the changes.

# chapter-6.xhtml:

- [x] Instead of having it in its own `<blockquote>`, you can move the header `The Baron of Grogzwig` into the following `<blockquote>`.
```
			<blockquote>
				<header>
					<p>The Baron of Grogzwig</p>
				</header>
				<p>“The Baron Von Koeldwethout, of Grogzwig in Germany, was as likely a young baron...</p>
			</blockquote>
```

# chapter-16.xhtml:

- [x] `MP` in `... the natural inquiry of <abbr epub:type="z3998:name-title">Mr.</abbr> Gregsbury, MP. ...` needs to be marked as an abbreviation.

# chapter-57.xhtml

- [x] - [ ] `MP` in `... eight young gentlemen, but they’re all MPs, ...` needs to be marked as an abbreviation.

# chapter-65.xhtml:

- [x] The bridgehead needs a period.

**Comment by drgrigg** [comment]
On your first point, I re-ran build-images, but it made no changes. What are you seeing?

**Comment by EmmaSweeney** [comment]
Sorry, I meant `se build-toc .` You changed the half title page and didn't update the ToC.

**Comment by drgrigg** [comment]
OK, that's done. Thanks, Emma!

**Comment by EmmaSweeney** [comment]
I found two more issues.

- [ ] Re-run `se clean .` and commit the change.

- [ ] In chapter 16, remove the period after `<abbr epub:type="z3998:initialism" class="eoc">M.P.</abbr>`

**Comment by drgrigg** [comment]
Whoops! (Note to self: always re-run clean and lint after a change requested by a reviewer!).

Both of these should now be fixed.
